[package]
name = "p5-exporting-a-convenient-public-api-with-pub-use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
