[package]
name = "p1-using-a-box-t-to-store-data-on-the-heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
