[package]
name = "p3-the-option-enum-and-its-advantages-over-null-values"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
