[package]
name = "p12-ignoring-an-unused-variable-by-starting-its-name-with-_"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
