[package]
name = "p5-a-shortcut-for-propogating-errors--the-questionmark-operator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
