[package]
name = "p5-having-multiple-owners-of-mutable-data-by-combining-rc-t-and-refcell-t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
