[package]
name = "p2-waiting-for-all-threads-to-finish-using-join-handles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
