[package]
name = "p5-using-the-newtype-pattern-to-implement-external-traits-on-external-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
