[package]
name = "r-3-4-defaults-or-or_else-get_or_insert-get_or_insert_with"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
