[package]
name = "p5-requesting-a-review-of-the-post-changes-its-state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
