[package]
name = "p13-ignoring-remaining-parts-of-a-value-with-dotdot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
