[package]
name = "p3-testing-equality-with-the-assert_eq-and-assert_ne-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
